//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikBot.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilgiler
    {
        public int id { get; set; }
        public string kAdi { get; set; }
        public string ePosta { get; set; }
        public string altEposta { get; set; }
        public Nullable<bool> mailGonderilsinmi { get; set; }
        public string sifre { get; set; }
        public string dosyaYolu { get; set; }
        public string gonderen { get; set; }
        public string gonderenSifre { get; set; }
        public string dosyaYoluTeam { get; set; }
        public string zaman { get; set; }
        public string sirketAdi { get; set; }
    }
}
